'''
Uses the weights as generated by the rl agent as coefficients to produce an observation for a ground telescope.
Configures each trained model and outputs both the weight producing model and the
'''

class Scheduler:
    def __init__(self):
        pass
